name: Deploy NestJS Backend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NEET }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            cd /home/neetell/neetall-be

            echo "Pulling latest code..."
            git pull origin master

            echo "Installing dependencies..."
            npm install

            echo "Generating Prisma Client..."
            npx prisma generate

            echo "Generating Prisma Schema..."
            npx prisma db push

            echo "Building NestJS..."
            npm run build

            echo "Restarting PM2..."
            pm2 restart neetall-be || pm2 start dist/main.js --name neetall-be
            pm2 save